--------------------------------------------------------------------------------
---------------------------------Load DIM_CUSTOMER ------------------------------
--------------------------------------------------------------------------------
-- ============================================================================
-- View Name   : gold.dim_customers
-- Description : This view creates a customer dimension table for analytics.
--               It combines customer information from CRM and ERP sources,
--               including personal details, marital status, country, gender,
--               birthdate, and account creation date.
-- 
-- Columns:
--   customer_key     : Surrogate key generated by ROW_NUMBER for uniqueness.
--   customer_id      : Customer ID from CRM_CUST_INFO.
--   customer_number  : Customer number from CRM_CUST_INFO.
--   first_name       : Customer's first name.
--   last_name        : Customer's last name.
--   marital_status   : Customer's marital status.
--   country          : Customer's country from ERP_LOC_A101.
--   gender           : Customer's gender, prioritizing CRM value, falling back to ERP or 'n/a'.
--   birthdate        : Customer's birthdate from ERP_CUST_AZ12.
--   create_date      : Customer account creation date.
--
-- Joins:
--   - SILVER.CRM_CUST_INFO (ci): Base customer info.
--   - SILVER.ERP_CUST_AZ12 (ec): Additional customer attributes (birthdate, gender).
--   - SILVER.ERP_LOC_A101 (el): Location information (country).
--
-- Notes:
--   - Gender is selected from CRM if available, otherwise from ERP or set to 'n/a'.
--   - LEFT JOINs ensure all CRM customers are included, even if ERP data is missing.
-- ============================================================================

IF OBJECT_ID('gold.dim_customers', 'V') IS NOT NULL
    DROP VIEW gold.dim_customers;
GO

CREATE VIEW gold.dim_customers AS  SELECT
        ROW_NUMBER() OVER(ORDER BY ci.cst_id) AS customer_key,
        ci.cst_id AS customer_id,
        ci.cst_key AS customer_number, 
        ci.cst_firstname AS first_name,
        ci.cst_lastname  AS last_name,
        ci.cst_marital_status  AS marital_status,
        el.CNTRY AS country,
        CASE 
            WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr 
            ELSE COALESCE(ec.GEN, 'n/a') 
        END AS gender,
        ec.BDATE AS birthdate,
        cst_create_date AS create_date
    FROM SILVER.CRM_CUST_INFO ci    
    LEFT JOIN  SILVER.ERP_CUST_AZ12 ec 
    ON ci.cst_key = ec.cid
    LEFT JOIN SILVER.ERP_LOC_A101 el
    ON ec.cid = el.cid
GO
-- SELECT * FROM  gold.dim_customers

--------------------------------------------------------------------------------
---------------------------------Load DIM_PRDOUCT ------------------------------
--------------------------------------------------------------------------------
/*
    View: gold.dim_products

    Description:
    This view creates a dimension table for products by combining product information from the CRM and ERP systems.
    It generates a unique surrogate key for each product and enriches product data with category and subcategory details.

    Columns:
    - product_key: Surrogate key generated using ROW_NUMBER for unique identification of each product.
    - product_id: Original product ID from the CRM product info table.
    - product_number: Product number from the CRM product info table.
    - product_name: Name of the product.
    - category_id: Category ID associated with the product.
    - category: Category name from the ERP category table.
    - subcategory: Subcategory name from the ERP category table.
    - maintenance: Maintenance information from the ERP category table.
    - product_line: Product line information.
    - cost: Product cost.
    - start_date: Product start date.

    Source Tables:
    - silver.crm_prd_info (aliased as cp): Contains product information.
    - silver.erp_px_cat_g1v2 (aliased as ep): Contains category and subcategory information.

    Joins:
    - LEFT JOIN on cp.cat_id = ep.id to enrich product data with category details.

    Filters:
    - Only includes products where prd_end_dt is NULL (i.e., excludes historical/inactive products).
*/
IF OBJECT_ID('gold.dim_products', 'V') IS NOT NULL
    DROP VIEW gold.dim_products;
GO

CREATE VIEW gold.dim_products AS
SELECT 
        ROW_NUMBER() OVER(ORDER BY cp.prd_start_dt , cp.prd_key) AS product_key,
        cp.prd_id As product_id, 
        cp.prd_key AS product_number,
        cp.prd_nm AS product_name,
        cp.cat_id  AS category_id, 
        ep.cat AS category,
        ep.subcat AS  subcategory ,
        ep.maintenance,
        prd_line AS product_line,
        cp.prd_cost AS cost ,
        cp.prd_start_dt AS start_date
FROM  silver.crm_prd_info cp
LEFT JOIN silver.erp_px_cat_g1v2 ep
ON cp.cat_id = ep.id
WHERE cp.prd_end_dt IS NULL -- Filter out all historical dat
GO

-- SELECT * FROM GOLD.DIM_PRODUCTS


--------------------------------------------------------------------------------
---------------------------------Load FACT_SALES ------------------------------
--------------------------------------------------------------------------------

-- =====================================================================================
-- View Name   : GOLD.FACT_SALES
-- Description : This view consolidates sales order details from the SILVER.crm_sales_details
--               table and enriches them with product and customer dimension data from
--               GOLD.DIM_PRODUCTS and GOLD.DIM_CUSTOMERS, respectively.
-- 
-- Columns:
--   - order_number   : Unique identifier for the sales order.
--   - product_key    : Surrogate key for the product from the product dimension.
--   - customer_key   : Surrogate key for the customer from the customer dimension.
--   - order_date     : Date when the sales order was placed.
--   - shipping_date  : Date when the sales order was shipped.
--   - due_date       : Date when the sales order is due.
--   - sales_amount   : Total sales amount for the order line.
--   - quantity       : Quantity of product sold.
--   - price          : Price per unit of the product.
--
-- Joins:
--   - LEFT JOIN to GOLD.DIM_PRODUCTS on product number to retrieve product dimension data.
--   - LEFT JOIN to GOLD.DIM_CUSTOMERS on customer ID to retrieve customer dimension data.
--
-- Usage      : Used for analytical reporting and business intelligence on sales data.
-- =====================================================================================

IF OBJECT_ID('GOLD.FACT_SALES', 'V') IS NOT NULL
    DROP VIEW GOLD.FACT_SALES;
GO

CREATE VIEW GOLD.FACT_SALES AS
    SELECT sls_ord_num AS order_number,
            dp.product_key,
            dc.customer_key,
            sls_order_dt AS order_date,
            sls_ship_dt AS  shipping_date,
            sls_due_dt AS due_date,
            sls_sales AS sales_amount,
            sls_quantity AS quantity,
            sls_price AS price
    FROM SILVER.crm_sales_details sd 
    LEFT JOIN GOLD.DIM_PRODUCTS dp
    ON sd.sls_prd_key = dp.product_number    
    LEFT JOIN [GOLD].[dim_customers] dc
    ON sd.sls_cust_id = dc.customer_id

GO
SELECT * FROM [GOLD].[FACT_SALES]  